from product import Products,Category

def unique_product(data_list):
    unique_category=()
    
    for i in data_list:
        unique_category+=(i._category)
    print(set(unique_category))

def sold_product_id(data_list):
    ids=[]
    for i in data_list:
        if i._quantity>0:
            ids.append(i._product_id)
    set(ids)
    print(ids)
    
def product_sales_data(data_list):
    data_dic={}
    for i in data_list:
        tup=()
        tup+=(i._product_name,i._price,i._quantity)
        data_dic.update({i._product_id:tup})
    print(data_dic)

def total_quantity(data_list):
    id=int(input("Enter Product ID to get quantity sold"))
    print(f"Total quantity sold with product id: {id}")
    for i in data_list:
        if i._product_id==id:
            print(i._quantity)
    
def average_product_price(data_list):
    sum=0
    id=int(input("Enter Product ID to get average of price"))
    for i in data_list:
        sum=sum+i._price
        if id==i._product_id:
            price=i._price
    average=price/sum
    print(f"average price of product id:{id} is {average}")

def electronics_products_names(data_list):
    product_names=[x._product_name for x in data_list if x._category==Category.Electronics and x._quantity>1]
    print(set(product_names))
    
def product_sales_generator(data_list):
    tup_data=()
    itr=(x for x in range(1,6))
    i=next(itr)
    tup_data+=(i._product_id,i._product_name,i._quantity)
    for i in tup_data:
        print(i)

def category_revenue(data_list):
    a=str(input("Enter category: \n press 0 for Electronics \n press 1 for computers"))
    revenue=0
    print(Category._category)
    if a==0:
        for i in data_list:
            revenue=revenue+i._price*i._quantity
            if Category._category==Category(a):
                print(f"Total revenue generated by Electronics is {revenue}")

    if a==1:
        for i in data_list:
            if Category._category==Category(a):
                revenue=revenue+(i._price*i._quantity)
                print(f"Total revenue generated by computers is {revenue}")